apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - image: processor
          imagePullPolicy: Always
          name: processor
          env:
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://discord-deputy-db-rw:5432/app
            - name: SPRING_R2DBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: discord-deputy-db-app
                  key: username
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: discord-deputy-db-app
                  key: password
            - name: RABBIT_HOST
              value: rabbitmq
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username 
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password 
          ports:
            - containerPort: 8085
              name: main
            - containerPort: 7085
              name: monitor
