apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - image: processor
          imagePullPolicy: Always
          name: processor
          env:
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: discord-deputy
                  key: mongo_user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: discord-deputy
                  key: mongo_pass
            - name: RABBIT_HOST
              value: rabbitmq
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username 
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password 
          ports:
            - containerPort: 8085
              name: main
            - containerPort: 7085
              name: monitor
