openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8082
    description: Generated server url
paths:
  /api/epicGames/currentOffers:
    get:
      tags:
        - epic-games-offer-controller
      operationId: getCurrentOffers
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Offer'
  /api/epicGames/allOffers:
    get:
      tags:
        - epic-games-offer-controller
      operationId: getAllOffers
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Offer'
  /api/epicGames/upcomingOffers:
    get:
      tags:
        - epic-games-offer-controller
      operationId: getUpcomingOffers
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Offer'
components:
  schemas:
    ImageUrl:
      type: object
      properties:
        url:
          type: string
        description:
          type: string
      description: A collection of various images relating to the offer
    Offer:
      required:
        - description
        - endTime
        - id
        - imageUrls
        - messageType
        - processTimestamp
        - source
        - sourceTimestamp
        - startTime
        - title
        - url
      type: object
      properties:
        messageType:
          type: string
          description: The type of message
          enum:
            - OFFER
            - NEWS
        sourceTimestamp:
          type: string
          description: The source timestamp of the message
          format: date-time
        processTimestamp:
          type: string
          description: The process timestamp of the message
          format: date-time
        source:
          type: string
          description: The source of the message
        id:
          type: string
          description: The unique identifier for the message
        title:
          type: string
          description: The offer title
        description:
          type: string
          description: A description about what the offering is
        url:
          type: string
          description: A URL pointing to where the offer can be found
        startTime:
          type: string
          description: The time when the offers starts to be in effect
          format: date-time
        endTime:
          type: string
          description: The time when the offers stops to be in effect
          format: date-time
        imageUrls:
          type: array
          description: A collection of various images relating to the offer
          items:
            $ref: '#/components/schemas/ImageUrl'
