version: '3.7'

services:
  grafana:
    image: grafana/grafana:7.3.0
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 3000:3000
    networks:
      - proxy-net

volumes:
  grafana_data: {}

networks:
  proxy-net:
    external:
      name: shared_net