apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: discord-deputy-db
spec:
  instances: 3
  storage:
    size: 5Gi
    storageClass: longhorn-single-replica
  postgresql:
    parameters:
      jsonb_pretty: "on"
  databases:
    - name: discordnotifications
      owner: postgres
