apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: discord-deputy-db
spec:
  instances: 3
  storage:
    size: 5Gi
    storageClass: longhorn-single-replica
  probes:
    liveness:
      periodSeconds: 20
      timeoutSeconds: 5
    readiness:
      periodSeconds: 20
      timeoutSeconds: 5