apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: discord-deputy-db
spec:
  instances: 3
  storage:
    size: 5Gi
    storageClass: longhorn-single-replica
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  postgresql:
    parameters:
      shared_buffers: "128MB"
  probes:
    liveness:
      periodSeconds: 30
      timeoutSeconds: 15
    readiness:
      periodSeconds: 30
      timeoutSeconds: 15
