server.port: 8083
management:
  endpoints:
    jmx.exposure.include: "*"
    web.exposure.include: "*"
  server.port: 7083
spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:rabbitmq}
    password: ${RABBIT_PASSWORD:rabbitmq}
  cloud:
    function.definition: sink
    stream.bindings:
      sink-in-0:
        destination: bot-notifications

discorddeputy.api.host:
  epicgames: ${API_HOST_EPIC_GAMES:http://localhost:8082}
  steam: ${API_HOST_STEAM:http://localhost:8084}