apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - image: rabbitmq:3.8.9-management
          name: rabbitmq
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: discord-deputy
                  key: rabbit_user
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: discord-deputy
                  key: rabbit_pass
          ports:
            - containerPort: 5672
              name: main
            - containerPort: 15672
              name: monitor
          volumeMounts:
            - name: rabbitmq-persistent-storage
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-persistent-storage
          persistentVolumeClaim:
            claimName: rabbitmq