apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq
spec:
  storageClassName: longhorn-single-replica
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi