apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 3
  persistence:
    storage: 2Gi
    storageClassName: longhorn-single-replica
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: '1'
      memory: 1Gi
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: rabbitmq
                startupProbe:
                  exec:
                    command:
                    - /bin/bash
                    - -c
                    - "rabbitmqctl eval 'rabbit_nodes:reached_target_cluster_size().' | grep -q '^true$'"
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  failureThreshold: 30
                  timeoutSeconds: 15
