version: '3.7'

services:
  bot:
    image: discorddeputy/bot:latest
    environment:
      RABBIT_HOST: rabbit
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      API_HOST_EPIC_GAMES: http://api-epic:8082
      API_HOST_STEAM: http://api-steam:8085

    ports:
      - 9083:8083
      - 7083:7083
    networks:
      - proxy-net

networks:
  proxy-net:
    external:
      name: shared_net