apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcher-epic
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - image: fetcher-epic
          imagePullPolicy: Always
          name: fetcher-epic
          env:
            - name: RABBIT_HOST
              value: rabbitmq
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password 
          ports:
            - containerPort: 8081
              name: main
            - containerPort: 7081
              name: monitor
