apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: fetcher-epic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fetcher-epic
  strategy:
    canary:
      maxUnavailable: 0
      maxSurge: 1
      steps:
        - analysis:
            templates:
              - templateName: producer-smoke-test-template
            args:
              - name: test-exchange-name
                value: "{{rollout.name}}-test-exchange"
        - setWeight: 100
  template:
    metadata:
      labels:
        app: fetcher-epic
    spec:
      containers:
        - name: fetcher-epic
          image: fetcher-epic
          env:
            - name: RABBIT_HOST
              value: rabbitmq
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
          ports:
            - containerPort: 8081
              name: main
              protocol: TCP
            - containerPort: 7081
              name: monitor
              protocol: TCP
