server.port: 8085
management:
  endpoints:
    jmx.exposure.include: "*"
    web.exposure.include: "*"
  server.port: 7085
spring:
  data.mongodb:
    authentication-database: admin
    database: steam
    host: ${MONGO_HOST:localhost}
    port: ${MONGO_PORT:27017}
    username: ${MONGO_USERNAME:mongodb}
    password: ${MONGO_PASSWORD:mongodb}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:rabbitmq}
    password: ${RABBIT_PASSWORD:rabbitmq}
  cloud.stream.bindings:
    input.destination: ${RABBIT_OUTPUT_DESTINATION:steamNews}
    output.destination: ${RABBIT_OUTPUT_DESTINATION:discordDeputy}