labels:
  - pairs:
      app: bot-interactive
    includeSelectors: true

resources:
  - deployment.yaml

images:
  - name: bot-interactive
    newName: freberg/discorddeputy-bot-interactive
    newTag: 0.5.1