apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcher-steam
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - image: fetcher-steam
          imagePullPolicy: Always
          name: fetcher-steam
          env:
            - name: RABBIT_HOST
              value: rabbitmq
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username 
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password 
          ports:
            - containerPort: 8084
              name: main
            - containerPort: 7084
              name: monitor
