server.port: 8082
management.port: 7082
spring:
  data.mongodb:
    authentication-database: admin
    database: epic
    host: ${MONGO_HOST:localhost}
    port: ${MONGO_PORT:27017}
    username: ${MONGO_USERNAME:mongodb}
    password: ${MONGO_PASSWORD:mongodb}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:rabbitmq}
    password: ${RABBIT_PASSWORD:rabbitmq}
  cloud.stream.bindings:
    input.destination: ${RABBIT_OUTPUT_DESTINATION:epicGamesOffers}
    output.destination: ${RABBIT_OUTPUT_DESTINATION:discordDeputy}