version: '3.7'

services:
  mongo:
    image: mongo:4.4.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - proxy-net

volumes:
  mongodb_data_container:

networks:
  proxy-net:
    name: "mongo_shared_net"