apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - image: api
          imagePullPolicy: Always
          name: api
          env:
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: discord-deputy
                  key: mongo_user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: discord-deputy
                  key: mongo_pass
            - name: RABBIT_HOST
              value: rabbitmq
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: discord-deputy
                  key: rabbit_user
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: discord-deputy
                  key: rabbit_pass
          ports:
            - containerPort: 8082
              name: main
            - containerPort: 7082
              name: monitor
