apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - image: api
          imagePullPolicy: Always
          name: api
          env:
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://discord-deputy-db-ro:5432/discordnotifications
            - name: SPRING_R2DBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: discord-deputy-db-superuser
                  key: username
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: discord-deputy-db-superuser
                  key: password
            - name: RABBIT_HOST
              value: rabbitmq
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
          ports:
            - containerPort: 8082
              name: main
            - containerPort: 7082
              name: monitor
