apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - port: 80
      targetPort: 8082
      name: main
    - port: 7082
      name: monitor
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: api-canary
spec:
  ports:
    - port: 80
      targetPort: 8082
      name: main
    - port: 7082
      name: monitor
  clusterIP: None