apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - image: mongo:4.4.1
          name: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: discord-deputy
                  key: mongo_user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: discord-deputy
                  key: mongo_pass
          ports:
            - containerPort: 27017
              name: main
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo
