apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data1/cluster/discord-deputy/mongo/"
