server.port: 8084
management:
  endpoints:
    jmx.exposure.include: "*"
    web.exposure.include: "*"
  endpoint:
    health:
      group:
        readiness:
          include: r2dbc
      show-details: always
  health:
    probes:
      enabled: true
  server.port: 7084
spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:rabbitmq}
    password: ${RABBIT_PASSWORD:rabbitmq}
  cloud.stream:
    bindings:
      newsSource-out-0:
        destination: source-notifications

steam:
  apps: 594650,252950
  pollFrequency:
    duration: 30
    timeUnit: MINUTES