version: '3.7'

services:
  rabbit:
    image: rabbitmq:3.8.9-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    labels:
      NAME: rabbitmq1
    networks:
      - proxy-net

networks:
  proxy-net:
    external:
      name: shared_net